CREATE TABLE [dbo].[Characters] (
    [CharacterId]   VARCHAR (50)  NOT NULL,
    [Username]      VARCHAR (50)  NOT NULL,
    [WeaponId]      INT           NULL,
    [ArmourId]      INT           NULL,
    [CharacterName] VARCHAR (100) NULL,
    [CharClass]     VARCHAR (50)  NULL,
    [CharLevel]     INT           NULL,
    [Gender]        CHAR (1)      NULL,
    [HP]            INT           NULL,
    [Mana]          INT           NULL,
    [Strength]      INT           NULL,
    [Dexterity]     INT           NULL,
    [Constitution]  INT           NULL,
    [Intelligence]  INT           NULL,
    [Wisdom]        INT           NULL,
    [Charisma]      INT           NULL,
    [SkillPoints]   INT           NULL,
    [StatPoints]    INT           NULL,
    [Speed]         INT           NULL,
    [Experience]    INT           NULL,
    [CarryWeight]   INT           NULL,
    PRIMARY KEY CLUSTERED ([CharacterId] ASC),
    CONSTRAINT [Armour_Deleted] FOREIGN KEY ([ArmourId]) REFERENCES [dbo].[Armour] ([ArmourId]) ON DELETE SET NULL,
    CONSTRAINT [User_Deleted] FOREIGN KEY ([Username]) REFERENCES [dbo].[Users] ([Username]) ON DELETE CASCADE,
    CONSTRAINT [Weapon_Deleted] FOREIGN KEY ([WeaponId]) REFERENCES [dbo].[Weapon] ([WeaponId]) ON DELETE SET NULL
);

