//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleDaata.DB_MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armour
    {
        public Armour()
        {
            this.Characters = new HashSet<Character>();
        }
    
        public int ArmourId { get; set; }
        public string Name { get; set; }
        public string ArmourType { get; set; }
        public string JobSpecific { get; set; }
        public Nullable<int> DefenseRate { get; set; }
        public Nullable<int> MagicDefense { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Attribute { get; set; }
        public string Enchantment { get; set; }
        public Nullable<int> MonetaryValue { get; set; }
        public string Rarity { get; set; }
    
        public virtual ICollection<Character> Characters { get; set; }
    }
}
