//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleDaata.DB_MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterSkill
    {
        public int CharacterSkillsId { get; set; }
        public int CharacterId { get; set; }
        public int SkillId { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
