//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSL_Dev_Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public Campaign()
        {
            this.Enemies = new HashSet<Enemy>();
            this.NPCs = new HashSet<NPC>();
            this.Characters = new HashSet<Character>();
        }
    
        public int CampaignId { get; set; }
        public string Username { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> NextSessionDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Enemy> Enemies { get; set; }
        public virtual ICollection<NPC> NPCs { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
    }
}
