//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSL_Dev_Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPC
    {
        public NPC()
        {
            this.Campaigns = new HashSet<Campaign>();
        }
    
        public int NPCId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Campaign> Campaigns { get; set; }
    }
}
