//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSL_Dev_Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spell
    {
        public Spell()
        {
            this.Characters = new HashSet<Character>();
        }
    
        public int SpellsId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CharClass { get; set; }
        public string Attribute { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Efficiency { get; set; }
        public Nullable<int> ManaRequired { get; set; }
        public Nullable<int> ChantingTime { get; set; }
    
        public virtual ICollection<Character> Characters { get; set; }
    }
}
