//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_BSL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignNPC
    {
        public int CampaignNPCId { get; set; }
        public int CampaignId { get; set; }
        public int NPCId { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual NPC NPC { get; set; }
    }
}
