//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_Final_SteveEd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public Campaign()
        {
            this.CampaignNPCs = new HashSet<CampaignNPC>();
            this.CampaignPlayers = new HashSet<CampaignPlayer>();
            this.CampaignEnemies = new HashSet<CampaignEnemy>();
        }
    
        public int CampaignId { get; set; }
        public int UsernameId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> NextSessionDate { get; set; }
    
        public virtual ICollection<CampaignNPC> CampaignNPCs { get; set; }
        public virtual ICollection<CampaignPlayer> CampaignPlayers { get; set; }
        public virtual ICollection<CampaignEnemy> CampaignEnemies { get; set; }
        public virtual User User { get; set; }
    }
}
