//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_Final_SteveEd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Campaigns = new HashSet<Campaign>();
            this.Characters = new HashSet<Character>();
        }
    
        public int UsernameId { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
    }
}
